name: Build
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  CiRunNumber: ${{ github.run_number }}
  CiRunName: ${{ github.ref }}-${{ github.event_name }}-ci${{ github.run_number }}  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: CiBuild
        env:
          CiBuildVersionSuffix: ${{ github.ref != 'refs/heads/main' && env.CiRunName || '' }}
        run: echo ${{ env.CiBuildVersionSuffix }}   
