name: Build
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  CiRunNumber: ${{ github.run_number }}
  CiRunName: ci${{ github.run_number }}
  CiBuildVersionSuffix: ${{ github.ref != 'refs/heads/main' && env.CiRunName || '' }}  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: CiBuild
        if: github.ref != 'refs/heads/main'
        env:
          CiBuildVersionSuffix:  ci${{ github.run_number }}
        run: echo "$(CiBuildVersionSuffix)"        
